// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://barvcgpcfgfwxtzirnjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcnZjZ3BjZmdmd3h0emlybmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjM0MDYsImV4cCI6MjA1NTk5OTQwNn0.R-LbPJH5pir5x5NIPH7XoIGgd8WQPK-w5B8Xxa4ai64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);